#!/usr/bin/env bash
#This script displays #s 1-100; displays "FizzBuzz" when # is multiple of 3 & 5, "Fizz" when # is multiple of 3, "Buzz" when # is multiple of 5.

j=1

for (( j=1; j<100; j++))
do
	if (( j % 3 == 0 && j % 5 == 0 ))
	then 
		echo "FizzBuzz"
	elif (( j % 3 == 0 ))
	then
		echo "Fizz"
	elif (( j % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$j"
	fi
done

	
