#!/usr/bin/env bash
#This is a script that displays contents of file /etc/passwd; will only display username, user id, home directory path for the user.

while read -r line;
do
	echo "$line" | cut -d ':' -f 1,3,6
done < /etc/passwd
