#!/usr/bin/env bash
#This script displays content of file /etc/passwd
IFS=":"
while read -r   
do
	echo "The user USERNAME is part of the GROUP_ID gang, lives in HOME_DIRECTORY and rides COMMAND/SHELL. USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO"
done < /etc/passwd
