#!/usr/bin/env bash
#This is a bash script that displays "Best School" 10 times, but for 9th iteration, displays "Best School" and then "Hi" on a new line
j=1
while [ $j -le 10 ]
do
    echo "Best School"
    if [ "$j" -eq 9 ]
    then
	echo "Hi"
    fi

    ((j++))
done
