#!/usr/bin/env bash
#This is a script that loops from 1 to 10 and displays: "bad luck" for 4th loop, "good luck" for 8th loop, and "Best School" for all other iterations
j=1
while [ $j -le 10 ]
do
    if [ "$j" -eq 4 ]
    then
	echo "bad luck"
    elif [ "$j" -eq 8 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi

    ((j++))
done
