#!/usr/bin/env bash
#This script displays #s from 1-20 and: displays "4" and then "bad luck from China" for 4th loop, displays "9" and then "bad luck from Japan" for 9th loop, displays "17" and then "bad luck from Italy" for 17th loop
j=1
while [ $j -le 20 ]
do
	case $j in
	
	4)
	echo "$j"
	echo "bad luck from China"
	;;
	
	9)
	echo "$j"
	echo "bad luck from Japan"
	;;

	17)
	echo "$j"
	echo "bad luck from Italy"
	;;

*)
	echo "$j"
	;;
	
	esac
	((j++))

done
