#!/usr/bin/env bash
#This is a script that displays time for 12 hrs and 59 min

j=0
h=0
while [ $j -le 779 ]
do
    if(( j % 60 == 0 ))
    then
      echo "Hour: $h"
      m=0
      ((h++))
    else
      echo "$m"
    fi
    ((j++))
    ((m++))
done
