#!/usr/bin/env bash
#This is a script that creates file and displays certain text; also the file that has been created will be deleted and terminates itself when receiving certain signals
sudo touch /var/run/holbertonscript.pid
sudo bash -c "echo $$ > /var/run/holbertonscript.pid"

trap interrup2 SIGINT
trap interrup1 SIGTERM
trap interrup3 SIGQUIT

interrup3()
{
    sudo rm /var/run/holbertonscript.pid
    exit $?
}

interrup2()
{
    echo "Y U no love me?!"
}

interrup1()
{
    echo "I hate the kill command"
    sudo rm /var/run/holbertonscript.pid
    exit $?
}

while true
do
    echo "To infinity and beyond"
    sleep 2
done
