#!/usr/bin/env bash
#This
case "$1" in
    start)
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
	;;
    stop)
	sudo kill -15 "$(cat /var/run/my_process.pid)"
	rm -f /var/run/my_process.pid
	echo "manage_my_process stopped"
	;;
    restart)
	sudo kill -15 "$(cat /var/run/my_process.pid)"
	rm -f /var/run/my_process.pid
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
	;;
    *)
	echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
exit 0
