#!/usr/bin/env bash
#This is a script that displays "To infinity and beyond" indefinitely with delayed iteration and also displays "I am invincible" when receiving a SIGTERM signal
while true
do
	echo "To infinity and beyond"
	sleep 2
if [ "$SIGTERM" ]
then
	echo "I am invincible!!!"
fi
done
